### ISSUE TITLE
How to use this mod?

### ISSUE THREAD

**Issue by OkinawaGaijin** [eth0net/enchant-menu#30]
Maybe a stupid question, but how to use this?

It does not change the standard enchantment table with a new gui
It doesn't have any keybinds i know of - not in mod description, not in the config, not in the keybind menu
It does not add a new table according to REI, so

I am completely clueless on how to get the GUI shown in your mod gallery.

Apologies in advance for the maybe stupid question. But I can't notice any change with this mod running compared to before.

Edit: your screenshots look like the vanilla inventory with the enchantment added? Then that might be a mod conflict, as I run a ton of mods, including playerEx and Trinkets, both make their own adjustments to the main inventory GUI, as well as mouse tweaks, inventory sorter and other things that add little buttons here and there.

**Comment by eth0net** [comment]
Apologies! I broke the keybinds and am just about to release a new fix with them registered :) You have to press X, but that was meant to show up in the controls settings page!

**Comment by eth0net** [comment]
Definitely not a stupid question, though! I need to add a wiki but been pushing on with development quickly and caused an issue 😅 I will add an entry to the README for now, and work on a wiki for more info later 😄 

Thanks for the feedback!

**Comment by eth0net** [comment]
Fixed version:

https://github.com/eth0net/enchant-menu/releases/tag/v1.2.1-beta%2Bfabric-1.19
