### ISSUE TITLE
[1.18.2] Crash when loading up world (Mod Incompatibility?)

### ISSUE THREAD

**Issue by ConqAra** [eth0net/enchant-menu#50]
Getting this Error:
![image](https://user-images.githubusercontent.com/76233356/198752747-53fd57b8-e468-46cc-82a4-a13b8aded8a7.png)

Full Log: [https://paste.ee/p/BAjd1](https://paste.ee/p/BAjd1)

**Comment by eth0net** [comment]
Hey, I suspect this is due to the completeconfig dependency 😄 You have 1.0.0 installed, but this was tested with 1.4.1 - could you try a later version of completeconfig?

**Comment by ConqAra** [comment]
Works Now 👍
